import type { Member }      from '@/types/member.types';
import type { Event }       from '@/types/event.types';
import type { Conversation } from '@/types/message.types';
import type { Application } from '@/types/application.types';

// ─────────────────────────────────────────────────────────────────
// MEMBERS
// ─────────────────────────────────────────────────────────────────

export const MEMBERS: Member[] = [
  {
    id:          1,
    name:        'Nadia Wolff',
    initials:    'NW',
    color:       '#4A3F35',
    role:        'Partner, Arcadia Capital',
    city:        'New York',
    bio:         'Investor turned advisor. Obsessed with the intersection of culture and capital. Weekend ceramicist.',
    tags:        ['Finance', 'Art', 'Design'],
    online:      true,
    memberSince: 'January 2023',
  },
  {
    id:          2,
    name:        'Rafael Osei',
    initials:    'RO',
    color:       '#7A8C6E',
    role:        'Creative Director, Studio Osei',
    city:        'London',
    bio:         'Making things that outlast trends. Leading a small studio building brands for the brave.',
    tags:        ['Design', 'Film', 'Architecture'],
    online:      false,
    memberSince: 'March 2023',
  },
  {
    id:          3,
    name:        'Soo-Jin Park',
    initials:    'SP',
    color:       '#9A7A45',
    role:        'Founder, Marigold Labs',
    city:        'Seoul',
    bio:         'Building the next chapter of human-computer interaction. Prev: MIT Media Lab, Google ATAP.',
    tags:        ['Tech', 'Design', 'Philosophy'],
    online:      true,
    memberSince: 'February 2023',
  },
  {
    id:          4,
    name:        'Marco Bellini',
    initials:    'MB',
    color:       '#B85C38',
    role:        'Author & Essayist',
    city:        'Milan',
    bio:         'Writing about time, memory, and cities. Three books, one Substack, zero social media.',
    tags:        ['Literature', 'Philosophy', 'Art'],
    online:      false,
    memberSince: 'April 2023',
  },
  {
    id:          5,
    name:        'Amara Diallo',
    initials:    'AD',
    color:       '#2D2926',
    role:        'Film Director',
    city:        'Paris',
    bio:         'Feature films, short films, and the spaces between. Currently in pre-production on my third feature.',
    tags:        ['Film', 'Art', 'Music'],
    online:      true,
    memberSince: 'January 2023',
  },
  {
    id:          6,
    name:        'James Kiprotich',
    initials:    'JK',
    color:       '#4A3F35',
    role:        'VP Product, Meridian',
    city:        'Nairobi',
    bio:         'Product leader who thinks in systems. Building tools for the next billion users.',
    tags:        ['Tech', 'Finance', 'Design'],
    online:      false,
    memberSince: 'May 2023',
  },
  {
    id:          7,
    name:        'Lena Voss',
    initials:    'LV',
    color:       '#7A8C6E',
    role:        'Architect, Voss & Partners',
    city:        'Berlin',
    bio:         'Spatial storytelling. Interested in how buildings shape behavior and behavior shapes buildings.',
    tags:        ['Architecture', 'Design', 'Philosophy'],
    online:      true,
    memberSince: 'June 2023',
  },
  {
    id:          8,
    name:        'Theo Nakamura',
    initials:    'TN',
    color:       '#9A7A45',
    role:        'Co-founder, Wren Studio',
    city:        'Tokyo',
    bio:         'Craft-obsessed builder. Making tools for the creative process. Avid home cook.',
    tags:        ['Tech', 'Design', 'Art'],
    online:      false,
    memberSince: 'July 2023',
  },
  {
    id:          9,
    name:        'Priya Mehta',
    initials:    'PM',
    color:       '#B85C38',
    role:        'Design Lead, Figma',
    city:        'San Francisco',
    bio:         'Design systems nerd. Building the invisible architecture that makes software feel alive.',
    tags:        ['Design', 'Art', 'Tech'],
    online:      true,
    memberSince: 'August 2023',
  },
  {
    id:          10,
    name:        'Sofia Almeida',
    initials:    'SA',
    color:       '#2D2926',
    role:        'Staff Writer, The Atlantic',
    city:        'Lisbon',
    bio:         'Covering culture, technology, and the things in between. Three cover stories last year.',
    tags:        ['Literature', 'Film', 'Philosophy'],
    online:      false,
    memberSince: 'September 2023',
  },
  {
    id:          11,
    name:        'Kai Hofmann',
    initials:    'KH',
    color:       '#4A3F35',
    role:        'Sound Designer',
    city:        'Berlin',
    bio:         'Designing sound for film and installation. Interested in how sound shapes space.',
    tags:        ['Music', 'Film', 'Tech'],
    online:      false,
    memberSince: 'October 2023',
  },
  {
    id:          12,
    name:        'Isabelle Morel',
    initials:    'IM',
    color:       '#7A8C6E',
    role:        'Chef & Restaurateur',
    city:        'Paris',
    bio:         'Three restaurants, one Michelin star, infinite opinions about butter.',
    tags:        ['Food & Wine', 'Design', 'Art'],
    online:      true,
    memberSince: 'November 2023',
  },
];

// ─────────────────────────────────────────────────────────────────
// EVENTS
// ─────────────────────────────────────────────────────────────────

export const EVENTS: Event[] = [
  {
    id:             1,
    day:            '12',
    month:          'May',
    type:           'Virtual',
    name:           'The Future of Creative Work',
    meta:           'Online · 6:00 PM EST · 90 min',
    desc:           'A conversation with four creatives building at the edges of their fields. What tools do they reach for? What do they wish existed? Moderated discussion, then open floor.',
    badge:          'virtual',
    attendeeColors: ['#4A3F35', '#7A8C6E', '#9A7A45'],
    attendeeCount:  42,
    attending:      false,
  },
  {
    id:             2,
    day:            '18',
    month:          'May',
    type:           'In Person',
    name:           'Dinner at Baraka, NYC',
    meta:           'New York · Tribeca · 7:30 PM',
    desc:           'An intimate dinner for 16 members. No agenda, no pitches. Just good food, natural wine, and honest conversation. Venue confirmed.',
    badge:          'inperson',
    attendeeColors: ['#2D2926', '#B85C38', '#7A8C6E'],
    attendeeCount:  14,
    attending:      true,
  },
  {
    id:             3,
    day:            '24',
    month:          'May',
    type:           'Virtual',
    name:           'Deep Dive: Urban Planning 2050',
    meta:           'Online · 2:00 PM CET · 2 hr',
    desc:           'Lena Voss and guests explore how cities will need to fundamentally redesign themselves for climate resilience and demographic shift over the next 30 years.',
    badge:          'virtual',
    attendeeColors: ['#9A7A45', '#4A3F35'],
    attendeeCount:  67,
    attending:      false,
  },
  {
    id:             4,
    day:            '03',
    month:          'Jun',
    type:           'In Person',
    name:           'Members Salon, London',
    meta:           'London · Mayfair · 7:00 PM BST',
    desc:           'Monthly salon for London-based members and visitors. This edition: the economics of taste. What determines cultural value and who gets to decide?',
    badge:          'inperson',
    attendeeColors: ['#7A8C6E', '#2D2926', '#B85C38'],
    attendeeCount:  22,
    attending:      false,
  },
  {
    id:             5,
    day:            '14',
    month:          'Jun',
    type:           'In Person',
    name:           'Summer Gathering, Berlin',
    meta:           'Berlin · Mitte · All day',
    desc:           'Our annual full-day gathering for European members. Morning workshops, afternoon conversations, evening dinner. Spots are extremely limited.',
    badge:          'sold',
    attendeeColors: ['#4A3F35', '#9A7A45', '#7A8C6E'],
    attendeeCount:  80,
    attending:      false,
  },
  {
    id:             6,
    day:            '22',
    month:          'Jun',
    type:           'Virtual',
    name:           'Writing in Public',
    meta:           'Online · 5:00 PM GMT · 60 min',
    desc:           'Marco Bellini and Sofia Almeida on the craft and anxiety of writing for an audience. From first drafts to published work — and the silence in between.',
    badge:          'virtual',
    attendeeColors: ['#B85C38', '#2D2926', '#4A3F35'],
    attendeeCount:  38,
    attending:      false,
  },
  {
    id:             7,
    day:            '08',
    month:          'Jul',
    type:           'In Person',
    name:           'Members Dinner, Tokyo',
    meta:           'Tokyo · Minami-Aoyama · 7:00 PM JST',
    desc:           'An evening for Tokyo-based members and those passing through the city. Private room at a kaiseki restaurant in Minami-Aoyama.',
    badge:          'inperson',
    attendeeColors: ['#9A7A45', '#7A8C6E'],
    attendeeCount:  11,
    attending:      false,
  },
];

// ─────────────────────────────────────────────────────────────────
// CONVERSATIONS
// ─────────────────────────────────────────────────────────────────

export const CONVERSATIONS: Conversation[] = [
  {
    id:              1,
    name:            'Nadia Wolff',
    initials:        'NW',
    color:           '#4A3F35',
    online:          true,
    unread:          true,
    lastMessage:     'That sounds like exactly the kind of project I\'d love to hear more about.',
    lastMessageTime: '2m',
    messages: [
      {
        from: 'them',
        text: 'Hey! I saw you were also attending the NYC dinner. Excited to finally meet in person.',
        time: 'Yesterday',
      },
      {
        from: 'me',
        text: 'Yes! Been looking forward to it. Are you flying in or based in New York?',
        time: '',
      },
      {
        from: 'them',
        text: 'I\'m based here, so no travel stress at least. Do you know who else is coming?',
        time: '',
      },
      {
        from: 'me',
        text: 'I think Lena Voss will be there — she\'s in town for a project.',
        time: 'Today',
      },
      {
        from: 'them',
        text: 'That sounds like exactly the kind of project I\'d love to hear more about.',
        time: '',
      },
    ],
  },
  {
    id:              3,
    name:            'Soo-Jin Park',
    initials:        'SP',
    color:           '#9A7A45',
    online:          true,
    unread:          true,
    lastMessage:     'I\'d love to connect on that research thread you mentioned.',
    lastMessageTime: '1h',
    messages: [
      {
        from: 'them',
        text: 'I read your thoughts on spatial computing from the last salon — really resonated.',
        time: 'Today',
      },
      {
        from: 'them',
        text: 'I\'d love to connect on that research thread you mentioned. Are you free this week?',
        time: '',
      },
    ],
  },
  {
    id:              2,
    name:            'Rafael Osei',
    initials:        'RO',
    color:           '#7A8C6E',
    online:          false,
    unread:          false,
    lastMessage:     'Thanks for the intro — she was amazing. We\'re already planning a collaboration.',
    lastMessageTime: '3h',
    messages: [
      {
        from: 'me',
        text: 'Did you end up connecting with Amara?',
        time: 'Yesterday',
      },
      {
        from: 'them',
        text: 'Thanks for the intro — she was amazing. We\'re already planning a collaboration.',
        time: 'Today',
      },
    ],
  },
  {
    id:              4,
    name:            'Marco Bellini',
    initials:        'MB',
    color:           '#B85C38',
    online:          false,
    unread:          false,
    lastMessage:     'The essay is almost done. You\'ll be one of the first to read it.',
    lastMessageTime: '1d',
    messages: [
      {
        from: 'them',
        text: 'The essay is almost done. You\'ll be one of the first to read it.',
        time: 'Yesterday',
      },
    ],
  },
  {
    id:              7,
    name:            'Lena Voss',
    initials:        'LV',
    color:           '#7A8C6E',
    online:          true,
    unread:          false,
    lastMessage:     'See you at the Berlin gathering — should be a good one.',
    lastMessageTime: '2d',
    messages: [
      {
        from: 'me',
        text: 'Are you going to the Berlin gathering in June?',
        time: '2 days ago',
      },
      {
        from: 'them',
        text: 'Wouldn\'t miss it — I\'m actually helping with one of the workshops.',
        time: '',
      },
      {
        from: 'me',
        text: 'That\'s incredible. Which one?',
        time: '',
      },
      {
        from: 'them',
        text: 'See you at the Berlin gathering — should be a good one.',
        time: '',
      },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────
// APPLICATIONS (seed — mirrors adminStore but kept here for
// use cases outside the admin flow, e.g. invite screens)
// ─────────────────────────────────────────────────────────────────

export const APPLICATIONS: Application[] = [
  {
    id:               1,
    firstName:        'Priya',
    lastName:         'Mehta',
    initials:         'PM',
    color:            '#4A3F35',
    role:             'Design Lead, Figma',
    city:             'San Francisco',
    appliedDate:      'Apr 23',
    status:           'pending',
    referralNote:     "Rafael's referral. Attended Berlin event.",
    bio:              'Design systems nerd. Building the invisible architecture that makes software feel alive.',
    interests:        ['Design', 'Art', 'Tech'],
    currentWork:      'Leading a cross-functional design systems team across 4 product areas.',
    communityMeaning: 'A place to learn from people who care about craft.',
    referralSource:   'Referred by a member',
  },
  {
    id:               2,
    firstName:        'Carlos',
    lastName:         'Rivera',
    initials:         'CR',
    color:            '#7A8C6E',
    role:             'Partner, Sequoia',
    city:             'New York',
    appliedDate:      'Apr 22',
    status:           'pending',
    referralNote:     'Referred by Nadia W. Strong background.',
    bio:              'Early-stage investor. Obsessed with founder psychology and category creation.',
    interests:        ['Finance', 'Tech', 'Philosophy'],
    currentWork:      'Leading a new fund focused on climate infrastructure.',
    communityMeaning: 'Honest conversation without pretense.',
    referralSource:   'Referred by a member',
  },
  {
    id:               3,
    firstName:        'Yuki',
    lastName:         'Tanaka',
    initials:         'YT',
    color:            '#9A7A45',
    role:             'Sculptor & Artist',
    city:             'Kyoto',
    appliedDate:      'Apr 20',
    status:           'pending',
    referralNote:     'Beautiful writing. Self-application, no referral.',
    bio:              'Working with bronze and digital fabrication. Interested in what materials remember.',
    interests:        ['Art', 'Philosophy', 'Architecture'],
    currentWork:      'A series of large-scale public sculptures exploring impermanence.',
    communityMeaning: 'Being around people who take ideas seriously.',
    referralSource:   'Social media',
  },
  {
    id:               4,
    firstName:        'Daniel',
    lastName:         'Greene',
    initials:         'DG',
    color:            '#B85C38',
    role:             'Product Manager, Stripe',
    city:             'Dublin',
    appliedDate:      'Apr 19',
    status:           'pending',
    referralNote:     'Referral from James K.',
    bio:              'Building financial infrastructure for the internet economy.',
    interests:        ['Tech', 'Finance', 'Design'],
    currentWork:      'Launching a new payments product for emerging markets.',
    communityMeaning: 'Meeting people who think in systems.',
    referralSource:   'Referred by a member',
  },
  {
    id:               5,
    firstName:        'Sofia',
    lastName:         'Almeida',
    initials:         'SA',
    color:            '#2D2926',
    role:             'Staff Writer, The Atlantic',
    city:             'Lisbon',
    appliedDate:      'Apr 18',
    status:           'pending',
    referralNote:     'Excellent essay responses.',
    bio:              'Covering culture, technology, and the things in between. Three cover stories last year.',
    interests:        ['Literature', 'Film', 'Philosophy'],
    currentWork:      'A long essay on how cities reshape identity.',
    communityMeaning: 'People who read carefully and argue well.',
    referralSource:   'Press coverage',
  },
  {
    id:               6,
    firstName:        'Kai',
    lastName:         'Hofmann',
    initials:         'KH',
    color:            '#4A3F35',
    role:             'Sound Designer',
    city:             'Berlin',
    appliedDate:      'Apr 17',
    status:           'pending',
    referralNote:     'Friend of member Amara D.',
    bio:              'Designing sound for film and installation. Interested in how sound shapes space.',
    interests:        ['Music', 'Film', 'Tech'],
    currentWork:      'Score for a feature documentary premiering at Cannes.',
    communityMeaning: 'Cross-disciplinary collision.',
    referralSource:   'Referred by a member',
  },
  {
    id:               7,
    firstName:        'Isabelle',
    lastName:         'Morel',
    initials:         'IM',
    color:            '#7A8C6E',
    role:             'Chef & Restaurateur',
    city:             'Paris',
    appliedDate:      'Apr 16',
    status:           'approved',
    referralNote:     'Runs critically acclaimed restaurant. Referral.',
    bio:              'Three restaurants, one Michelin star, infinite opinions about butter.',
    interests:        ['Food & Wine', 'Design', 'Art'],
    currentWork:      'Opening a fourth concept focused on natural wine.',
    communityMeaning: 'People who care about making things well.',
    referralSource:   'Referred by a member',
  },
  {
    id:               8,
    firstName:        'Owen',
    lastName:         'Park',
    initials:         'OP',
    color:            '#9A7A45',
    role:             'Climate Scientist, MIT',
    city:             'Boston',
    appliedDate:      'Apr 15',
    status:           'rejected',
    referralNote:     'Impressive research background.',
    bio:              'Studying tipping points in climate systems. Occasional writer.',
    interests:        ['Sustainability', 'Philosophy', 'Tech'],
    currentWork:      'Research on permafrost carbon feedback loops.',
    communityMeaning: 'Rigorous thinkers from different fields.',
    referralSource:   'Press coverage',
  },
];

// ─────────────────────────────────────────────────────────────────
// CONFIG
// ─────────────────────────────────────────────────────────────────

export const APP_CONFIG = {
  name:             'INNER',
  tagline:          'Where remarkable people gather',
  maxInvitesPerYear: 3,
  acceptanceRate:    12,
  reviewDays:        14,
} as const;